import { GetStaticProps } from "next";
import Head from "next/head";
import { BlogCard } from "~/components/blog/card";
import Hero from "~/components/hero";
import { SEO } from "~/components/seo";
import Layout from "~/layouts/base";
import { Frontmatter } from "~/types/blog";
import { getAllBlogsFrontmatter } from "~/utils/blogs";

type Props = {
  blogs: Frontmatter[];
};
export default function Home({ blogs }: Props) {
  return (
    <>
      <Head>
        <title>iamyadav.com</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <SEO title="iamyadav" />
      <Layout>
        <main>
          <Hero />
          <h1 className="text-2xl font-bold mb-4">Latest writings</h1>
          {blogs.map((blog) => (
            <BlogCard key={blog.slug} {...blog} />
          ))}
        </main>
      </Layout>
    </>
  );
}

export const getStaticProps: GetStaticProps = async () => {
  const blogs = await getAllBlogsFrontmatter();
  return { props: { blogs: blogs.slice(0, 5) } };
};
